---
- hosts: localhost
  gather_facts: False
  tasks:
    - shell: 'date +%Y%m%d%H%M%S'
      register: current_run_timestamp
      tags:
      - always

- hosts: dbsvrs
  gather_facts: False
  roles:
    - { role: dbsvrs-common }
    - { role: instana-repo,  when: instana_repo_enabled }
    - { role: instana-jre }

- hosts: zookeeper_node
  gather_facts: True
  roles:
    - { role: instana-zookeeper }

- hosts: kafka_node
  gather_facts: True
  roles:
    - { role: instana-kafka }

- hosts: clickhouse_node
  gather_facts: True
  roles:
    - { role: instana-clickhouse }

- hosts: cockroachdb_node
  gather_facts: True
  roles:
    - { role: instana-cockroachdb }

- hosts: cassandra_node
  gather_facts: True
  roles:
    - { role: instana-cassandra }

## elasticsearch installation: convert group_vars es setting for preload before role execution
- hosts: localhost
  gather_facts: false
  tasks:
    - name: generate es master node var file.
      copy:
        content: "{{ elasticsearch.config_master_node | to_nice_yaml }}"
        dest: "elasticsearch.config_master_node.yml"
    - name: generate es data node var file.
      copy:
        content: "{{ elasticsearch.config_data_node | to_nice_yaml }}"
        dest: "elasticsearch.config_data_node.yml"
- hosts: elasticsearch_node
  gather_facts: True
  roles:
    - { role: instana-elasticsearch }
