---
cockroachdb:
  java_home: "{{ instana_java_home }}"
  version: 21.1.7
  cluster_mode: insecure #  please use insecure for instana config
  cluster_master: "{{play_hosts[0]}}" # will use the first node in ck node list as master
  install_dir: /opt/cockroachdb
  download_mirror: https://binaries.cockroachdb.com
  # https://binaries.cockroachdb.com/cockroach-v21.1.7.linux-amd64.tgz
  configuration:
    port: 26257
    http_port: 8001  # make sure not occupied as k8s nginx ingress will use 8081
    data_dir: /mnt/data/cockroachdb
    log_dir: /var/log/cockroachdb
    certs_dir: /mnt/data/cockroachdb/certs
    cache: 512MiB
    max_sql_memory: 512MiB
    #locality: "region=eu,datacenter=eu-west-1"
