## All in One setup for every Instana datastore component

# Instana Agent Key
instana_agent_key: qUMhYJxjSv6uZh2SyqTEnw
instana_repo_enabled: yes
package_download_path : "/opt/images/"

# Instana JRE
instana_java_package: instana-jre-11-11.0.7-1
instana_java_home: /opt/instana/jre11

zookeeper_client_port: 2181  # {{ zookeeper.configuration.client_port }} ,pick this var out here as it will be used for zookeeper, kafka, clickhouse

#-------------------
# zookeeper settings
#-------------------
zookeeper:
  version: 3.6.3
  install_dir: /opt/zookeeper
  download_mirror: https://archive.apache.org/dist/zookeeper
  configuration:
    heap_size: 2048
    jvmflags: '-XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled'
    client_port: 2181
    data_dir: /mnt/data/zookeeper
    conf_dir: /etc/zookeeper
    log_dir: /var/log/zookeeper
    log_file: zookeeper.log
    log_level: INFO
    log_max_file_size: 265MB
    log_max_backup_index: 20
    max_client_cnxns: 0
    tick_time: 2000
    init_limit: 10
    sync_limit: 5
    autopurge_snapretain_count: 20
    purge_interval: 1
    members: "{{ groups['zookeeper_node'] | map('extract', hostvars, 'ansible_default_ipv4') | map(attribute='address') | list }}"
    member_id: "{{ ansible_default_ipv4.address }}"

#----------------
# kafka settings
#----------------
kafka:
  version: 2.7.1
  scala_version: 2.13
  install_dir: /opt/kafka
  download_mirror: https://archive.apache.org/dist/kafka
  configuration:
    port: 9092
    conf_dir: /etc/kafka
    data_dir: /mnt/data/kafka
    log_dir: /var/log/kafka
    delete_topic_enable: true
    replication_factor: 1
    network_threads: 3
    disk_threads: 8
    num_partitions: 3
    so_snd_buff_bytes: 102400
    so_rcv_buff_bytes: 102400
    so_request_max_bytes: 104857600
    data_dir_recovery_threads: 1
    log_retention_hours: 24
    log_retention_bytes: 1073741824
    log_segment_bytes: 1073741824
    log_retention_check_interval: 300000
    log_cleaner_enable: false
    zk_connection_timeout: 60000

#--------------------
# clickhouse settings
#--------------------
clickhouse:
  # For server.xml.j2
  version: 21.3.8.76
  data_dir: /mnt/traces/clickhouse
  log_dir: "/var/log/clickhouse-server"
  logger_level: information
  logger_size: 200M
  logger_count: 10
  http_port: 8123
  tcp_port: 9000
  dynamic_file: /etc/clickhouse-server/dynamic.xml
  interserver_http_port: 9009
  listen_host:
    - "0.0.0.0"
  configuration:
    max_connections: 16384
    keep_alive_timeout: 3
    max_concurrent_queries: 100
    uncompressed_cache_size: 8589934592
    mark_cache_size: 5368709120
    builtin_dictionaries_reload_interval: 3600
    max_session_timeout: 3600
    default_session_timeout: 60
  # For dynamic.xml.j2
  cluster_name: local
  shards:
    0:
      - { host: "cinst-k1.fyre.ibm.com", port: 9000 }
      - { host: "cinst-k2.fyre.ibm.com", port: 9000 }
    #1:
    #  - { host: "cinst-k3.fyre.ibm.com", port: 9000 }
    #  - { host: "cinst-k4.fyre.ibm.com", port: 9000 }
  zknodes:
    - { host: "9.112.255.160", port: 2181 }
    - { host: "9.112.255.163", port: 2181 }
    - { host: "9.123.116.50", port: 2181 }

#---------------------
# cockroachdb settings
#---------------------
cockroachdb:
  version: 21.1.7
  cluster_mode: insecure #  please use insecure for instana config
  cluster_master: "{{play_hosts[0]}}" # will use the first node in ck node list as master
  install_dir: /opt/cockroachdb
  download_mirror: https://binaries.cockroachdb.com
  # eg. https://binaries.cockroachdb.com/cockroach-v21.1.7.linux-amd64.tgz
  configuration:
    port: 26257
    http_port: 8001  # make sure not occupied as k8s nginx ingress will use 8081
    data_dir: /mnt/data/cockroachdb
    log_dir: /var/log/cockroachdb
    certs_dir: /mnt/data/cockroachdb/certs
    cache: 512MiB
    max_sql_memory: 512MiB

#-------------------
# cassandra settings
#-------------------
cassandra:
  java_home: "{{ instana_java_home }}" # consider to replace back to jre8, now just fix jre11 options, need more test
  version_catogory: "311x"
  version: 3.11.10
  download_mirror: https://archive.apache.org/dist/cassandra
  # eg.: https://archive.apache.org/dist/cassandra/redhat/311x/cassandra-3.11.10-1.noarch.rpm
  cluster_name: "onprem"
  configuration:
    conf_dir: /etc/cassandra
    data_dir: /mnt/metrics/cassandra
    log_dir: /var/log/cassandra
    max_heap_size: 16G
    heap_newsize: 4G
    fd_limit: 1048576
    jvm_opts: "-Dcassandra.allow_unsafe_aggressive_sstable_expiration=true -XX:+IgnoreUnrecognizedVMOptions" # fix jre11 issue

#-----------------------
# elasticsearch settings
#-----------------------
# For distributed es cluster, configure master & data node seperately.
# Especially check the node.master & node.data vars, to be match hostvars[es_role] defined in the inventory file
elasticsearch:
  config_master_node:
    es_version: "7.10.2" # instana required.
    es_heap_size: "3g"  # instana required.
    es_data_dirs: # instana required.
      - "/mnt/data/elasticsearch/data"
    es_log_dir: "/mnt/logs/elasticsearch" # instana required.
    es_config:
      cluster.name: "test-cluster" # instana required.
      cluster.initial_master_nodes: "cinst-k1.fyre.ibm.com" # <node.name>:<port>,<node.name>:<port> (typically the node names of the clusters dedicated masters)
      discovery.seed_hosts: "cinst-k1.fyre.ibm.com:9300" # <host>:<port>,<host>:<port> (typically the clusters dedicated masters)
      http.host: 0.0.0.0
      http.port: 9200
      node.data: false
      node.master: true
      transport.host: 0.0.0.0
      transport.port: 9300
      bootstrap.memory_lock: true # instana required.
    es_plugins:
     - plugin: ingest-attachment
  config_data_node:
    es_version: "7.10.2" # instana required.
    es_heap_size: "2g"  # instana required.
    es_data_dirs: # instana required.
      - "/mnt/data/elasticsearch/data"
    es_log_dir: "/mnt/logs/elasticsearch"
    es_config:
      cluster.name: "test-cluster" # instana required.
      cluster.initial_master_nodes: "cinst-k1.fyre.ibm.com" # <node.name>:<port>,<node.name>:<port> (typically the node names of the clusters dedicated masters)
      discovery.seed_hosts: "cinst-k1.fyre.ibm.com:9300" # <host>:<port>,<host>:<port> (typically the clusters dedicated masters)
      http.host: 0.0.0.0
      http.port: 9200
      node.data: true
      node.master: false
      transport.host: 0.0.0.0
      transport.port: 9300
      bootstrap.memory_lock: true # instana required
    es_plugins:
      - plugin: ingest-attachment

# Other settings
proxy_env:
  http_proxy: "{{ http_proxy | default ('') }}"
  HTTP_PROXY: "{{ http_proxy | default ('') }}"
  https_proxy: "{{ https_proxy | default ('') }}"
  HTTPS_PROXY: "{{ https_proxy | default ('') }}"
  no_proxy: "{{ no_proxy | default ('') }}"
  NO_PROXY: "{{ no_proxy | default ('') }}"
