---
kafka:
  java_home: "{{ instana_java_home }}"
  version: 2.7.1
  scala_version: 2.13
  install_dir: /opt/kafka
  #download_mirror: http://apache.rediris.es/kafka
  download_mirror: https://archive.apache.org/dist/kafka
  configuration:
    port: 9092
    conf_dir: /etc/kafka
    data_dir: /mnt/data/kafka
    log_dir: /var/log/kafka
    delete_topic_enable: true
    replication_factor: 1
    network_threads: 3
    disk_threads: 8
    num_partitions: 3
    so_snd_buff_bytes: 102400
    so_rcv_buff_bytes: 102400
    so_request_max_bytes: 104857600
    data_dir_recovery_threads: 1
    log_retention_hours: 24
    log_retention_bytes: 1073741824
    log_segment_bytes: 1073741824
    log_retention_check_interval: 300000
    log_cleaner_enable: false
    zk_connection_timeout: 60000
  members: "{{ groups['kafka_node'] | map('extract', hostvars, 'ansible_default_ipv4') | map(attribute='address') | list }}"
  member_id: "{{ ansible_default_ipv4.address }}"
