---
- name: Backup existing cockroachdb data directories
  include: ../../dbsvrs-common/tasks/backup_dir.yml
  loop: 
    - "{{ cockroachdb.configuration.data_dir }}"
    - "{{ cockroachdb.configuration.log_dir }}"
  when: skip_databackup|default(False) == False

- name: Clean the cockroachdb data directories
  include: ../../dbsvrs-common/tasks/clean_dir.yml
  loop: 
    - "{{ cockroachdb.configuration.data_dir }}"
    - "{{ cockroachdb.configuration.log_dir }}"
