---
- name: Enable ZooKeeper
  systemd:
    name: zookeeper
    enabled: yes
    state: started
    daemon_reload: yes
  listen: Update ZooKeeper

- name: Restart ZooKeeper
  systemd:
    name: zookeeper
    state: restarted
  listen: Update ZooKeeper
